#!/bin/bash
export BUILD_ARCH="-arch x86_64 -msse4.1 -mmacosx-version-min=10.15"
export PKG_BUILD_SUFFIX="-osx10.11-x64"
#export BUILD_ARCH="-arch arm64 -mmacosx-version-min=11.0"
#export PKG_BUILD_SUFFIX="-osx11-arm64"

if ! command -v brew &> /dev/null
then
    echo "brew not found but required"
    echo "install brew with:"
    echo "  /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)\""
    exit 1

    # brew may be later uninstalled with
    #   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
fi

brew install autoconf
brew install automake
brew install pkg-config
brew install libtool
brew install pcre
brew install openssl
ln -s ../opt/openssl/include/openssl /usr/local/include/openssl

cd cvsnt-2.5.05.3744
autoreconf -i --force
if [ $? != 0 ]; then
  echo "ERROR: autoconf failed!"
  exit 2
fi

cd zstd
CFLAGS="$BUILD_ARCH" LDFLAGS="$BUILD_ARCH" make clean install
cd ..

cd osx
./build-mac
if [ $? != 0 ]; then
  echo "ERROR: build-mac failed!"
  exit 3
fi
cd ../..
