#!/bin/sh 
# cvslockd - cvsnt lock daemon 
# 
# chkconfig: 345 35 65 
# description: Handles file level locking for the cvsnt server
# processname: cvslockd
# pidfile: /var/run/cvslockd.pid 
# Do not load RH compatibility interface. 
WITHOUT_RC_COMPAT=1

# Source function library. 
. /etc/init.d/functions

DAEMON=/usr/bin/cvslockd
LOCKFILE=/var/lock/subsys/cvslockd
PIDFILE=/var/run/cvslockd.pid
RETVAL=0

start()
{
        start_daemon --lockfile "$LOCKFILE" --pidfile "$PIDFILE" -- $DAEMON
	RETVAL=$?
        return $RETVAL
}

stop()
{
        stop_daemon --lockfile "$LOCKFILE" -- $DAEMON
	RETVAL=$?
        return $RETVAL
}
			
restart() {
	stop
	start
}	


case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    reload|restart)
	restart
	;;
    condstop)
        if [ -e "$LOCKFILE" ]; then
	    stop
	fi
	;;
    condrestart)
        if [ -e "$LOCKFILE" ]; then
	    restart
	fi
	;;
    condreload)
        if [ -e "$LOCKFILE" ]; then
	    reload
	fi
	;;
    status)
	status -- $DAEMON
	RETVAL=$?
	;;
    *)
        msg_usage "${0##*/} {start|stop|reload|restart|condstop|condrestart|condreload|status}"
	RETVAL=1
esac

exit $RETVAL
