#!/bin/bash
set -x
set -v
BuildPackage=0
BuildODBC=0
PackageName="g-cvsnt"

if [ "$1" = "--ODBC" ]; then
	BuildODBC=1
	echo "Cannot build ODBC on native Mac OS 10.4 - ignoring."
	shift
fi
if [ "$1" = "--nopackage" ]; then
	BuildPackage=0
	shift
fi

SourceRoot="${1-`pwd`}"
Distribution_Dir=$SourceRoot/Distribution_folder
InstallerResources=$Distribution_Dir/Resources
InstallerRoot=$Distribution_Dir/Package_Root
InstallerFilesInfo=$Distribution_Dir/Info.plist
InstallerFilesDescription=$Distribution_Dir/Description.plist
InstallerFiles=$SourceRoot/InstallerFiles
PackageMakerPath=/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker

export DYLD_LIBRARY_PATH=$InstallerRoot/usr/local/lib

rm -rf $Distribution_Dir

SAVEDIR=`pwd`
cd $SourceRoot/..
make clean
./configure --prefix=/usr/local --with-config-dir=/private/etc/cvsnt CC="clang" CPP="clang -E" CXX="clang++" LDFLAGS="-m64" CPPFLAGS="-m64" --with-internal-zlib CXXFLAGS="-arch x86_64 -D__DARWIN_OS__=`uname -r | sed s/'\.[0-9,\.]*$'//`" CFLAGS="-D__DARWIN_OS__=`uname -r | sed s/'\.[0-9,\.]*$'//`" --disable-odbc --disable-ltdl --disable-postgres --disable-server --disable-mysql --disable-sspi --disable-sqlite --disable-odbc --enable-64bit
rm -rf $InstallerRoot/* 
make -j8 install DESTDIR=$InstallerRoot
# make install DESTDIR=$InstallerRoot
cd $SAVEDIR

if [ $BuildPackage -eq 1 ]; then
	BUILD=`$InstallerRoot/usr/local/bin/cvsnt ver -q`
	ShortVer=`echo $BUILD | sed s/'\.[0-9]*$'//`

	BaseName=$PackageName-$BUILD
	InstallerPackageName=$SourceRoot/$BaseName.pkg
	DmgFileName=$SourceRoot/$BaseName-intel.dmg
	
	rm -rf $InstallerPackageName
	rm -rf $DmgFileName
	rm -rf $InstallerResources
	
	rm -f $InstallerRoot/usr/local/lib/*.la
	rm -f $InstallerRoot/usr/local/lib/cvsnt/database/*.la
	rm -f $InstallerRoot/usr/local/lib/cvsnt/mdns/*.la
	rm -f $InstallerRoot/usr/local/lib/cvsnt/protocols/*.la
	rm -f $InstallerRoot/usr/local/lib/cvsnt/triggers/*.la
	rm -f $InstallerRoot/usr/local/lib/cvsnt/xdiff/*.la

	cp -r $InstallerFiles/private $InstallerRoot
	cp -r $InstallerFiles/Library $InstallerRoot
	cp -r $InstallerFiles/InstallerResources $InstallerResources
	cp -r $InstallerFiles/install_copy_cvsnt.sh $Distribution_Dir
	
	sed "s/%CVSNT_VERSION%/$BUILD/g" <$InstallerFiles/Info.plist |
	sed "s/%CVSNT_SHORTVERSION%/$ShortVer/g" >$InstallerFilesInfo
	sed "s/%CVSNT_VERSION%/$BUILD/g" <$InstallerFiles/Description.plist |
	sed "s/%CVSNT_SHORTVERSION%/$ShortVer/g" >$InstallerFilesDescription
	
	find $InstallerRoot -name .DS_Store -exec rm -f {} \; 2>/dev/null
	find $InstallerRoot -type d -name CVS -exec rm -rf {} \; 2>/dev/null
	
	rm cvsnt-$BUILD.tar.gz
	cd Distribution_folder
	tar -czvpf ../cvsnt-$BUILD.tar.gz *
	cd ..

	echo $PackageMakerPath -build -p $InstallerPackageName -f $InstallerRoot -r $InstallerResources -i $InstallerFilesInfo -d $InstallerFilesDescription
	
	echo hdiutil create -fs HFS+ -format UDZO -volname $BaseName -imagekey zlib-level=9 -ov -srcfolder $InstallerPackageName $DmgFileName
	echo rm -rf $InstallerPackageName
fi
