etc/cvsnt/*
usr/bin/cvs
usr/bin/cvsnt
usr/bin/cvsscript
usr/lib/cvsnt/protocols/*.so
usr/lib/cvsnt/protocols/*.la
usr/lib/cvsnt/triggers/*.so
usr/lib/cvsnt/triggers/*.la
usr/lib/cvsnt/xdiff/*.so
usr/lib/cvsnt/xdiff/*.la
usr/lib/libcvsapi.so
usr/lib/libcvstools.so
usr/lib/libcvsapi-3.5.15.7699.so
usr/lib/libcvsapi.la
usr/lib/libcvstools-3.5.15.7699.so
usr/lib/libcvstools.la
usr/share/man/man[15]/*

