#!/bin/bash
if   [ "configure" = "$1" ] && [ "." = ".$2" ]; then shift ; set -- "1" "$@"
elif [ "configure" = "$1" ] && [ "." != ".$2" ]; then shift ; set -- "2" "$@"
fi
if [ "configure" = "$1" ]; then
    chmod 755 /var/cache/cafs
    chown cvs:cvs /var/cache/cafs
fi
# no systemd in a container or chroot: nothing to reload there
if [ -d /run/systemd/system ]; then /usr/bin/systemctl daemon-reload; fi
