#!/bin/sh
# UFC-crypt: ultra fast crypt(3) implementation
# Copyright (C) 1991, 1992, Free Software Foundation, Inc.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the Free
# Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# @(#)do_ranlib	1.2 02/12/92
#
# Frontend to the ranlib command
#

if [ -f /bin/ranlib -o -f /usr/bin/ranlib -o -f /usr/ucb/ranlib ] 
then
	echo ranlib libufc.a
	ranlib libufc.a
else 
	echo "Couldn't find a ranlib command - skipping ranlib"
fi

exit 0
